services:
  realtime:
    build: .
    container_name: fluig-realtime
    depends_on:
      - fluig
    command: ["${FLUIG_INSTALL_PATH}/node/bin/node", "${FLUIG_INSTALL_PATH}/node/realtime.js"]
    volumes:
      - fluig-app-data:${FLUIG_INSTALL_PATH}
    ports:
      - "${PORT_REALTIME}:8888"
      - "${PORT_CHAT}:7070"
    networks:
      - fluig-net
