services:
  indexer:
    build: .
    container_name: fluig-indexer
    depends_on:
      - fluig
    command: ["${FLUIG_INSTALL_PATH}/solr/bin/solr", "start", "-f"]
    volumes:
      - fluig-app-data:${FLUIG_INSTALL_PATH}
    ports:
      - "${PORT_SOLR}:8983"
    networks:
      - fluig-net
